services:
  # Copy node_modules to host for IDE support
  setup:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/host
    command: cp -r /app/node_modules /host/
    
  # Development service with ng serve
  angular_dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run start -- --host 0.0.0.0 --port 4200 --poll 2000 --live-reload --disable-host-check
    stdin_open: true
    tty: true

  # Production build service
  angular_build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./dist:/app/dist
    command: npm run build

  # Production serve with nginx
  angular_prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    depends_on:
      - angular_build 